; C64 BOOTSTRAP PROGRAM SEARCHES FOR A STRING 'CBM80' FROM ADDRESS $8004
; WHEN THE COMPUTER STARTS. IF IT IS FOUND (I.E. A CARTRIDGE IS INSERTED - OR
; MEMORY STILL CONTAINS GARBAGE IF COMPUTER WAS NOT OFF LONG ENOUGH FOR
; THE RAM TO VAPORIZE), EXECUTION JUMPS TO A COLDSTART VECTOR WHICH 
; IS SPECIFIED AT LOCATION $8000. AFTER THAT THE WARMSTART VECTOR 
; DEFINED IN $8002 IS EXECUTED, AND PROGRAM STARTS.

* = $8000
     WORD COLDSTART
     WORD WARMSTART
     BYTE $C3,$C2,$CD,$38,$30  ; CBM8O
 
COLDSTART ; CARTRIDGE PROGRAM MUST FINISH THE COMPUTER INITIALIZATION
     SEI
     STX $D016 ; TURN ON VIC FOR PAL/NTSC CHECK
     JSR $FDA3 ; IRQ
     JSR $FD50 ; INITIALIZE MEMORY
     JSR $FD15 ; INITIALIZE I/O
     JSR $FF5B ; INITIALIZE VIC
     CLI
 
WARMSTART ; HERE STARTS OUR OWN PROGRAM

CHANGE_BORDER_COLOR ; FLASHING COLORS - TRADITIONAL C64 ASSEMBLY HELLO WORLD
     INC $D020
     JMP CHANGE_BORDER_COLOR

; FILL THE REST WITH ZEROS TO GET 8K FILE
* = $9FFF
     BYTE 0